import { useState, useEffect, useRef } from 'react'
import { useParams, Link, useNavigate } from 'react-router-dom'
import CodeEditor          from '../../components/CodeEditor/CodeEditor.jsx'
import LivePreview, { buildSandboxHTML } from '../../components/LivePreview/LivePreview.jsx'
import CustomizePanel      from '../../components/CustomizePanel/CustomizePanel.jsx'
import AdSense             from '../../components/AdSense/AdSense.jsx'
import { getAnimationById, getAnimations } from '../../hooks/useAnimations.js'
import { useSEO } from '../../hooks/useSEO.js'
import './AnimationDetail.css'

const SPEEDS = [
  { label:'0.25x', value:0.25 },
  { label:'0.5x',  value:0.5  },
  { label:'1x',    value:1    },
  { label:'2x',    value:2    },
  { label:'4x',    value:4    },
]

// ─── Download Utilities ─────────────────────────────────────
function slugify(str) {
  return (str||'animation').toLowerCase().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'').slice(0,40)
}
function downloadFile(content, filename) {
  const blob = new Blob([content],{type:'text/plain;charset=utf-8'})
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href = url; a.download = filename
  document.body.appendChild(a); a.click()
  document.body.removeChild(a); URL.revokeObjectURL(url)
}
function buildHTMLFile(title, cssCode, jsCode, bg) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
  <title>${title} — MotionZync</title>
  <style>
    *,*::before,*::after{margin:0;padding:0;box-sizing:border-box;}
    body{background:${bg||'#0a0a0f'};overflow:hidden;}
    #container{width:100vw;height:100vh;position:relative;}
${cssCode.split('\n').map(l=>'    '+l).join('\n')}
  </style>
</head>
<body>
  <div id="container"></div>
  <!-- Generated by MotionZync — https://motion-zync.vercel.app -->
  <script>
${jsCode}
  </script>
</body>
</html>`
}

// ─── Animated BG ────────────────────────────────────────────
function DetailBg({ hue=260 }) {
  const cvRef = useRef(null)
  useEffect(() => {
    const cv = cvRef.current; if (!cv) return
    const ctx = cv.getContext('2d')
    let id, t = 0
    function resize() { cv.width=cv.offsetWidth||window.innerWidth; cv.height=cv.offsetHeight||window.innerHeight }
    resize()
    window.addEventListener('resize', resize, { passive:true })
    function draw() {
      const W=cv.width, H=cv.height
      ctx.clearRect(0,0,W,H)
      const bx=W*0.3+Math.sin(t*0.4)*W*0.2, by=H*0.3+Math.cos(t*0.3)*H*0.15
      const g1=ctx.createRadialGradient(bx,by,0,bx,by,W*0.45)
      g1.addColorStop(0,`hsla(${hue},70%,45%,0.09)`); g1.addColorStop(1,'transparent')
      ctx.fillStyle=g1; ctx.fillRect(0,0,W,H)
      const bx2=W*0.7+Math.cos(t*0.35)*W*0.18, by2=H*0.65+Math.sin(t*0.28)*H*0.2
      const g2=ctx.createRadialGradient(bx2,by2,0,bx2,by2,W*0.35)
      g2.addColorStop(0,`hsla(${(hue+40)%360},65%,50%,0.07)`); g2.addColorStop(1,'transparent')
      ctx.fillStyle=g2; ctx.fillRect(0,0,W,H)
      t+=0.007; id=requestAnimationFrame(draw)
    }
    draw()
    return () => { cancelAnimationFrame(id); window.removeEventListener('resize',resize) }
  }, [hue])
  return <canvas ref={cvRef} className="detail-bg-canvas"/>
}

// ─── Loading ────────────────────────────────────────────────
function LoadingScreen() {
  const cvRef = useRef(null)
  useEffect(() => {
    const cv=cvRef.current; if(!cv) return
    const ctx=cv.getContext('2d'); cv.width=120; cv.height=120
    let t=0, id
    function draw() {
      ctx.clearRect(0,0,120,120)
      for(let i=3;i>=1;i--){const r=i*18+Math.sin(t*2+i)*4;ctx.beginPath();ctx.arc(60,60,r,0,Math.PI*2);ctx.strokeStyle=`rgba(124,58,237,${0.2+(4-i)*0.2})`;ctx.lineWidth=2;ctx.stroke()}
      ctx.beginPath();ctx.arc(60,60,42,t*2,t*2+Math.PI*1.2);ctx.strokeStyle='#7c3aed';ctx.lineWidth=3;ctx.lineCap='round';ctx.stroke()
      ctx.beginPath();ctx.arc(60,60,5,0,Math.PI*2);ctx.fillStyle='#a78bfa';ctx.fill()
      t+=0.05; id=requestAnimationFrame(draw)
    }
    draw(); return ()=>cancelAnimationFrame(id)
  },[])
  return (
    <div className="detail-loading">
      <canvas ref={cvRef}/>
      <span>Loading animation...</span>
    </div>
  )
}

// ─── Breadcrumb ─────────────────────────────────────────────
function Breadcrumb({ title }) {
  const ref=useRef(null)
  useEffect(()=>{ const el=ref.current; if(!el) return; setTimeout(()=>el.classList.add('bc-in'),60) },[])
  return (
    <div ref={ref} className="detail-breadcrumb bc-anim">
      <Link to="/gallery" className="bc-link">← Gallery</Link>
      <span className="bc-sep">›</span>
      <span className="bc-cur">{title}</span>
    </div>
  )
}

// ─── Header ─────────────────────────────────────────────────
function DetailHeader({ anim, copied, onShare }) {
  const ref=useRef(null)
  useEffect(()=>{ const el=ref.current; if(!el) return; setTimeout(()=>el.classList.add('dh-in'),100) },[])
  return (
    <div ref={ref} className="detail-header dh-anim">
      <div className="dh-left">
        <div className="dh-cat-row">
          <span className="detail-cat">{anim.category}</span>
        </div>
        <h1 className="detail-title">{anim.title}</h1>
        {anim.description && <p className="detail-desc">{anim.description}</p>}
        <div className="detail-tags">
          {anim.tags?.slice(0,5).map(t=><span key={t} className="detail-tag">#{t}</span>)}
        </div>
      </div>
      <div className="dh-actions">
        <button className={`dh-btn ${copied==='link'?'copied':''}`} onClick={onShare}>
          {copied==='link'?'✅ Copied!':'🔗 Share'}
        </button>
        <Link to={`/compare?a=${anim.docId}`} className="dh-btn">⚖️ Compare</Link>
        <Link to={`/wallpaper?id=${anim.docId}`} className="dh-btn">🖼️ Wallpaper</Link>
        <Link to="/playground" className="dh-btn dh-btn-primary">⚡ Playground</Link>
      </div>
    </div>
  )
}

// ─── Speed ──────────────────────────────────────────────────
function SpeedControl({ speed, onChange }) {
  return (
    <div className="speed-bar">
      <span className="speed-label">⚡ Playback Speed</span>
      <div className="speed-btns">
        {SPEEDS.map(s=>(
          <button key={s.value} className={`speed-btn ${speed===s.value?'active':''}`} onClick={()=>onChange(s.value)}>
            {s.label}
          </button>
        ))}
      </div>
    </div>
  )
}

// ─── Copy + Download Row ────────────────────────────────────
function CopyRow({ cssCode, jsCode, copied, onCopy, animTitle, animBg, onDownload, downloaded }) {
  return (
    <div className="copy-row">
      <button className={`copy-btn ${copied==='css'?'copied':''}`} onClick={()=>onCopy(cssCode,'css')}>
        {copied==='css'?'✅ CSS Copied!':'📋 Copy CSS'}
      </button>
      <button className={`copy-btn ${copied==='js'?'copied':''}`} onClick={()=>onCopy(jsCode,'js')}>
        {copied==='js'?'✅ JS Copied!':'📋 Copy JS'}
      </button>
      <button className={`copy-btn copy-all-btn ${copied==='all'?'copied':''}`} onClick={()=>onCopy(`/* CSS */\n${cssCode}\n\n/* JS */\n${jsCode}`,'all')}>
        {copied==='all'?'✅ All Copied!':'📋 Copy All'}
      </button>
      <div className="copy-divider"/>
      <button className={`copy-btn dl-btn ${downloaded==='css'?'dl-done':''}`} onClick={()=>onDownload('css')} title="CSS file download">
        {downloaded==='css'?'✅ Downloaded!':'⬇️ CSS'}
      </button>
      <button className={`copy-btn dl-btn ${downloaded==='js'?'dl-done':''}`} onClick={()=>onDownload('js')} title="JS file download">
        {downloaded==='js'?'✅ Downloaded!':'⬇️ JS'}
      </button>
      <button className={`copy-btn dl-btn dl-html-btn ${downloaded==='html'?'dl-done':''}`} onClick={()=>onDownload('html')} title="Complete HTML file">
        {downloaded==='html'?'✅ Downloaded!':'⬇️ HTML'}
      </button>
    </div>
  )
}

// ─── Fullscreen Preview ──────────────────────────────────────
function FullscreenModal({ cssCode, jsCode, bgColor, speed, onClose }) {
  const iframeRef = useRef(null)
  const overlayRef = useRef(null)

  useEffect(() => {
    const t = setTimeout(() => {
      if (iframeRef.current)
        iframeRef.current.srcdoc = buildSandboxHTML(cssCode, jsCode, bgColor, speed)
    }, 80)
    // ESC to close
    function onKey(e) { if (e.key === 'Escape') onClose() }
    document.addEventListener('keydown', onKey)
    // Prevent body scroll
    document.body.style.overflow = 'hidden'
    return () => {
      clearTimeout(t)
      document.removeEventListener('keydown', onKey)
      document.body.style.overflow = ''
    }
  }, [cssCode, jsCode, bgColor, speed])

  return (
    <div
      ref={overlayRef}
      className="fs-overlay"
      onClick={e => { if (e.target === overlayRef.current) onClose() }}
    >
      <div className="fs-container">
        {/* Top bar */}
        <div className="fs-topbar">
          <div className="fs-dots">
            <span className="fs-dot fs-dot-red"/>
            <span className="fs-dot fs-dot-yellow"/>
            <span className="fs-dot fs-dot-green"/>
          </div>
          <span className="fs-label">⛶ Fullscreen Preview</span>
          <div className="fs-bar-right">
            <span className="fs-esc-hint">ESC to close</span>
            <button className="fs-close-btn" onClick={onClose} title="Close">✕</button>
          </div>
        </div>
        {/* Full iframe */}
        <iframe
          ref={iframeRef}
          className="fs-iframe"
          sandbox="allow-scripts"
          title="fullscreen preview"
        />
      </div>
    </div>
  )
}

// ─── Preview Frame ───────────────────────────────────────────
function PreviewFrame({ cssCode, jsCode, bgColor, speed }) {
  const [loaded,      setLoaded]      = useState(false)
  const [fullscreen,  setFullscreen]  = useState(false)

  useEffect(()=>{ setTimeout(()=>setLoaded(true),200) },[])

  return (
    <>
      <div className={`preview-frame ${loaded?'frame-in':''}`}>
        <div className="preview-frame-header">
          <div className="frame-dots">
            <div className="frame-dot fd-red"/><div className="frame-dot fd-yellow"/><div className="frame-dot fd-green"/>
          </div>
          <div className="frame-url">
            <span className="frame-url-icon">🔒</span>
            <span>motion-zync.vercel.app / preview</span>
          </div>
          <div className="frame-header-right">
            <div className="frame-live"><span className="live-blink">●</span> LIVE</div>
            {/* Fullscreen button */}
            <button
              className="frame-fs-btn"
              onClick={() => setFullscreen(true)}
              title="Fullscreen ma juo"
            >
              ⛶
            </button>
          </div>
        </div>
        <LivePreview cssCode={cssCode} jsCode={jsCode} bgColor={bgColor} speed={speed}/>
      </div>

      {fullscreen && (
        <FullscreenModal
          cssCode={cssCode} jsCode={jsCode}
          bgColor={bgColor} speed={speed}
          onClose={() => setFullscreen(false)}
        />
      )}
    </>
  )
}

// ─── Floating Bar ────────────────────────────────────────────
function FloatingBar({ copied, downloaded, onCopyAll, onDownloadAll }) {
  const [visible, setVisible] = useState(false)
  const [dlOpen,  setDlOpen]  = useState(false)
  const dlRef = useRef(null)
  useEffect(()=>{
    function onScroll(){ setVisible(window.scrollY>320) }
    window.addEventListener('scroll',onScroll,{passive:true})
    return ()=>window.removeEventListener('scroll',onScroll)
  },[])
  useEffect(()=>{
    function onDown(e){ if(dlRef.current&&!dlRef.current.contains(e.target)) setDlOpen(false) }
    document.addEventListener('mousedown',onDown)
    return ()=>document.removeEventListener('mousedown',onDown)
  },[])
  return (
    <div className={`floating-bar ${visible?'fb-visible':''}`}>
      <button className={`fb-btn ${copied==='all'?'fb-copied':''}`} onClick={onCopyAll}>
        {copied==='all'?'✅ Copied!':'📋 Copy Code'}
      </button>
      <div className="fb-dl-wrap" ref={dlRef}>
        <button className={`fb-btn fb-dl-btn ${downloaded?'fb-copied':''}`} onClick={()=>setDlOpen(p=>!p)}>
          {downloaded?'✅ Downloaded!':'⬇️ Download'}
        </button>
        {dlOpen && (
          <div className="fb-dl-menu">
            <button className="fb-dl-opt" onClick={()=>{onDownloadAll('css');setDlOpen(false)}}>
              <span className="fb-dl-icon">🎨</span>
              <span className="fb-dl-text"><strong>.css</strong><small>Stylesheet only</small></span>
            </button>
            <button className="fb-dl-opt" onClick={()=>{onDownloadAll('js');setDlOpen(false)}}>
              <span className="fb-dl-icon">⚙️</span>
              <span className="fb-dl-text"><strong>.js</strong><small>Script only</small></span>
            </button>
            <button className="fb-dl-opt fb-dl-opt-html" onClick={()=>{onDownloadAll('html');setDlOpen(false)}}>
              <span className="fb-dl-icon">🌐</span>
              <span className="fb-dl-text"><strong>.html</strong><small>Complete — browser ma open thay</small></span>
            </button>
          </div>
        )}
      </div>
    </div>
  )
}

// ─── How To Use ──────────────────────────────────────────────
function HowToUse({ anim }) {
  const ref=useRef(null)
  useEffect(()=>{
    const el=ref.current; if(!el) return
    const io=new IntersectionObserver(([e])=>{ if(e.isIntersecting){el.classList.add('howto-in');io.disconnect()} },{threshold:0.1})
    io.observe(el); return ()=>io.disconnect()
  },[])
  return (
    <div ref={ref} className="detail-howto howto-anim">
      <h2 className="howto-title">📖 How to Use This Animation</h2>
      <div className="howto-steps">
        <div className="howto-step">
          <div className="step-num-badge">1</div>
          <div><strong>Copy or Download</strong><p>CSS, JS copy karo — ya <strong>.html download</strong> karo, browser ma direct open thase</p></div>
        </div>
        <div className="howto-step">
          <div className="step-num-badge">2</div>
          <div><strong>Add to HTML</strong><p>Container div banavo — ID <code>container</code> sathe</p></div>
        </div>
        <div className="howto-step">
          <div className="step-num-badge">3</div>
          <div><strong>Paste Code</strong><p>CSS → <code>&lt;style&gt;</code> tag ma, JS → <code>&lt;script&gt;</code> tag ma</p></div>
        </div>
      </div>
      <div className="howto-code-block">
        <div className="howto-code-label">HTML Template</div>
        <pre><code>{`<div id="container" style="width:100%;height:400px;
  position:relative;overflow:hidden;
  background:${anim.previewBg||'#0a0a0f'};"></div>
<style>/* Paste CSS yahan */</style>
<script>/* Paste JS yahan */</script>`}</code></pre>
      </div>
      <p className="howto-tip">💡 Full-screen background mate container ne <code>position:fixed; inset:0; z-index:-1;</code> set karo</p>
    </div>
  )
}

// ═══════════════════════════════════════════════════════════
// ─── RELATED ANIMATIONS (Fixed) ─────────────────────────────
// ═══════════════════════════════════════════════════════════

// Improved token extractor — focuses on DISTINCTIVE tokens
function extractSignature(css='', js='') {
  const sig = new Set()

  // 1. @keyframes names — very distinctive
  const kfNames = css.match(/@keyframes\s+([\w-]+)/g) || []
  kfNames.forEach(k => sig.add(k.replace('@keyframes','').trim()))

  // 2. CSS custom properties (--var-name)
  const cssVars = css.match(/--[\w-]+/g) || []
  cssVars.forEach(v => sig.add(v))

  // 3. Canvas / WebGL calls in JS (specific methods)
  const canvasMethods = js.match(/ctx\.(arc|bezierCurveTo|quadraticCurveTo|lineTo|moveTo|fillRect|strokeRect|createRadialGradient|createLinearGradient|drawImage|fillText|strokeText|createPattern)\b/g) || []
  canvasMethods.forEach(m => sig.add(m))

  // 4. CSS transform functions used
  const transforms = css.match(/(translateX|translateY|translate3d|rotate3d|rotateX|rotateY|scaleX|scaleY|skewX|skewY|perspective)\s*\(/g) || []
  transforms.forEach(t => sig.add(t.replace('(','').trim()))

  // 5. Specific animation properties: timing functions
  const timings = (css+' '+js).match(/(cubic-bezier|spring|elastic|bounce|ease-in-out|steps\(\d)/g) || []
  timings.forEach(t => sig.add(t))

  // 6. JS: distinctive variable names (camelCase, 6+ chars, no generic)
  const SKIP = new Set(['function','return','const','let','var','this','Math','window','document',
    'undefined','null','true','false','length','width','height','canvas','context',
    'requestAnimationFrame','cancelAnimationFrame','addEventListener','appendChild',
    'createElement','querySelectorAll','getElementById','innerHTML','style','forEach'])
  const jsVars = js.match(/\b[a-z][a-zA-Z]{5,}\b/g) || []
  jsVars.forEach(v => { if(!SKIP.has(v)) sig.add(v) })

  // 7. Color patterns (hsl, rgba usage patterns)
  if (css.includes('hsl(') || js.includes('hsl(')) sig.add('__hsl__')
  if (css.includes('rgba(') || js.includes('rgba(')) sig.add('__rgba__')
  if (js.includes('canvas') || js.includes('Canvas')) sig.add('__canvas__')
  if (css.includes('@keyframes')) sig.add('__keyframes__')
  if (js.includes('particle') || js.includes('Particle')) sig.add('__particles__')
  if (js.includes('noise') || js.includes('perlin')) sig.add('__noise__')
  if (css.includes('clip-path')) sig.add('__clippath__')
  if (css.includes('filter:') || css.includes('filter :')) sig.add('__filter__')
  if (js.includes('THREE') || js.includes('three')) sig.add('__three__')
  if (js.includes('gsap') || js.includes('GSAP')) sig.add('__gsap__')
  if (js.includes('svg') || js.includes('SVG')) sig.add('__svg__')

  return sig
}

function codeSimilarity(a, b) {
  const sigA = extractSignature(a.cssCode||'', a.jsCode||'')
  const sigB = extractSignature(b.cssCode||'', b.jsCode||'')
  if (!sigA.size && !sigB.size) return 0
  if (!sigA.size || !sigB.size) return 0
  let common = 0
  sigA.forEach(t => { if (sigB.has(t)) common++ })
  // Jaccard similarity
  const union = new Set([...sigA, ...sigB])
  return common / union.size
}

// Mini iframe preview
function MiniPreview({ cssCode, jsCode, bg }) {
  const iframeRef = useRef(null)
  useEffect(() => {
    // Small delay so DOM is ready
    const t = setTimeout(() => {
      if (iframeRef.current) {
        iframeRef.current.srcdoc = buildSandboxHTML(cssCode, jsCode, bg)
      }
    }, 150)
    return () => clearTimeout(t)
  }, [cssCode, jsCode, bg])
  return (
    <iframe
      ref={iframeRef}
      className="related-iframe"
      sandbox="allow-scripts"
      title="related preview"
    />
  )
}

function RelatedAnimations({ currentAnim }) {
  const [related,  setRelated]  = useState([])
  const [loading,  setLoading]  = useState(true)
  const [visible,  setVisible]  = useState(false)
  const sectionRef = useRef(null)

  useEffect(() => {
    if (!currentAnim?.docId) return
    let cancelled = false

    getAnimations().then(all => {
      if (cancelled) return
      const others = all.filter(a => a.docId !== currentAnim.docId)

      // Score each animation
      const scored = others.map(a => ({
        ...a,
        score: codeSimilarity(currentAnim, a),
      }))

      // Sort by score descending
      scored.sort((a, b) => b.score - a.score)

      // Take top 4 — threshold very low (0.01) to always get results
      // If even that fails, fallback to same category
      let top = scored.filter(a => a.score > 0.01).slice(0, 4)

      if (top.length < 2) {
        // Fallback: same category
        const sameCat = others.filter(a => a.category === currentAnim.category).slice(0, 4)
        if (sameCat.length > 0) {
          top = sameCat.map(a => ({ ...a, score: 0 }))
        } else {
          // Last resort: just take first 4
          top = others.slice(0, 4).map(a => ({ ...a, score: 0 }))
        }
      }

      setRelated(top)
      setLoading(false)

      // Show with a short delay after render
      setTimeout(() => setVisible(true), 100)
    })

    return () => { cancelled = true }
  }, [currentAnim?.docId])

  if (loading || related.length === 0) return null

  return (
    <div
      ref={sectionRef}
      className={`related-section ${visible ? 'related-in' : ''}`}
    >
      <div className="related-header">
        <div className="related-line"/>
        <h2 className="related-title">
          <span className="related-icon">⚡</span>
          Similar Animations
          {related[0]?.score > 0 && <span className="related-badge">By Code</span>}
          {related[0]?.score === 0 && <span className="related-badge related-badge-cat">Same Category</span>}
        </h2>
        <div className="related-line"/>
      </div>

      <div className="related-grid">
        {related.map((anim, i) => (
          <Link
            key={anim.docId}
            to={`/animation/${anim.docId}`}
            className="related-card"
            style={{ animationDelay: `${i * 0.09}s` }}
          >
            <div className="related-preview" style={{ background: anim.previewBg||'#1a1a28' }}>
              <MiniPreview cssCode={anim.cssCode} jsCode={anim.jsCode} bg={anim.previewBg}/>
              {anim.score > 0 && (
                <div className="related-score-badge">{Math.round(anim.score*100)}% match</div>
              )}
            </div>
            <div className="related-info">
              <span className="related-cat">{anim.category}</span>
              <span className="related-name">{anim.title}</span>
            </div>
          </Link>
        ))}
      </div>
    </div>
  )
}

// ─── Main Component ──────────────────────────────────────────
export default function AnimationDetail() {
  const { id }       = useParams()
  const navigate     = useNavigate()
  const [anim,       setAnim]       = useState(null)
  const [cssCode,    setCssCode]    = useState('')
  const [jsCode,     setJsCode]     = useState('')
  const [speed,      setSpeed]      = useState(1)
  const [copied,     setCopied]     = useState('')
  const [downloaded, setDownloaded] = useState('')
  const [loading,    setLoading]    = useState(true)

  useEffect(() => {
    if (!id) return
    getAnimationById(id).then(data => {
      if (!data) { setLoading(false); return }
      setAnim(data); setCssCode(data.cssCode||''); setJsCode(data.jsCode||'')
      setLoading(false)
    })
  }, [id])

  useSEO(anim ? {
    title: `${anim.title} — Free ${anim.category} CSS/JS Animation | MotionZync`,
    description: anim.description?.trim()
      ? anim.description
      : `${anim.title} — a free, copy-paste ready ${anim.category} animation from MotionZync. Live preview with full CSS & JS source included.`,
    url: `https://motion-zync.vercel.app/animation/${id}`,
  } : {})

  async function copy(text, which) {
    await navigator.clipboard.writeText(text)
    setCopied(which); setTimeout(()=>setCopied(''), 2200)
  }

  function handleDownload(type) {
    const slug = slugify(anim?.title)
    if (type==='css')  downloadFile(cssCode, `${slug}.css`)
    if (type==='js')   downloadFile(jsCode,  `${slug}.js`)
    if (type==='html') downloadFile(buildHTMLFile(anim?.title,cssCode,jsCode,anim?.previewBg), `${slug}.html`)
    setDownloaded(type); setTimeout(()=>setDownloaded(''), 2500)
  }

  function shareLink() {
    navigator.clipboard.writeText(window.location.href)
    setCopied('link'); setTimeout(()=>setCopied(''), 2200)
  }

  if (loading) return <LoadingScreen/>
  if (!anim)   return (
    <div className="detail-loading">
      <span>❌ Animation not found.</span>
      <Link to="/gallery" className="dh-btn" style={{marginTop:'1rem'}}>← Gallery</Link>
    </div>
  )

  const bgHue = parseInt((anim.previewBg||'#0a0a0f').replace('#',''),16)%360||260

  return (
    <div className="detail-page page-section">
      <DetailBg hue={bgHue}/>
      <div className="container detail-container">
        <Breadcrumb title={anim.title}/>
        <DetailHeader anim={anim} copied={copied} onShare={shareLink}/>
        <AdSense slot={import.meta.env.VITE_ADSENSE_SLOT_PLAYGROUND}/>
        <SpeedControl speed={speed} onChange={setSpeed}/>

        <div className="detail-split">
          <PreviewFrame cssCode={cssCode} jsCode={jsCode} bgColor={anim.previewBg} speed={speed}/>
          <div className="detail-code-pane">
            <CopyRow
              cssCode={cssCode} jsCode={jsCode}
              copied={copied}   onCopy={copy}
              animTitle={anim.title} animBg={anim.previewBg}
              onDownload={handleDownload} downloaded={downloaded}
            />
            <CodeEditor cssCode={cssCode} jsCode={jsCode} onCssChange={setCssCode} onJsChange={setJsCode}/>
          </div>
        </div>

        <CustomizePanel cssCode={cssCode} jsCode={jsCode} onChange={(c,j)=>{setCssCode(c);setJsCode(j)}}/>
        <AdSense slot={import.meta.env.VITE_ADSENSE_SLOT_PLAYGROUND}/>
        <HowToUse anim={anim}/>

        {/* Related Animations — fixed */}
        <RelatedAnimations currentAnim={{ ...anim, cssCode, jsCode }}/>
      </div>

      <FloatingBar
        copied={copied} downloaded={downloaded}
        onCopyAll={()=>copy(`/* CSS */\n${cssCode}\n\n/* JS */\n${jsCode}`,'all')}
        onDownloadAll={handleDownload}
      />
    </div>
  )
  }
    
