import {useMemo,useState} from 'react'
import {useSearchParams} from 'react-router-dom'
import {searchCatalog} from './engine.js'
import {accessLabel} from './access.js'
import './DesignIntelligence.css'
const DOMAINS=[['all','All'],['styles','Styles'],['palettes','Palettes'],['typography','Typography'],['charts','Charts'],['stacks','Stacks'],['recipes','Recipes']]
export default function DesignIntelligenceExplorer(){
  const [params]=useSearchParams();const [query,setQuery]=useState(params.get('q')||'');const [domain,setDomain]=useState(params.get('domain')||'all');const results=useMemo(()=>searchCatalog(query,domain),[query,domain])
  return <div className="di-page"><section className="di-page-intro"><span className="di-kicker">EXPLORE</span><h1>Search the knowledge core</h1><p>Start with plain language or a domain name. The current engine is deterministic; semantic AI search can improve it later without replacing the core.</p></section><section className="di-surface"><label className="di-label" htmlFor="di-search">Search</label><input id="di-search" className="di-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try: dark developer dashboard, healthcare, premium, React"/><div className="di-chip-row" role="group" aria-label="Knowledge domain">{DOMAINS.map(([id,label])=><button key={id} className={'di-chip '+(domain===id?'active':'')} aria-pressed={domain===id} onClick={()=>setDomain(id)}>{label}</button>)}</div></section><div className="di-result-grid">{results.map(item=><article className={'di-record '+(item.tier!=='free'?'is-locked':'')} key={item.id}><div className="di-record-head"><span className="di-record-domain">{item.domain||item.category}</span><span className={'di-tier tier-'+item.tier}>{accessLabel(item.tier)}</span></div><h2>{item.name}</h2><p>{item.description||item.purpose||item.layout||item.focus?.join(' · ')||((item.heading||'')+' + '+(item.body||''))}</p><div className="di-tags">{(item.tags||item.focus||[]).slice(0,5).map(tag=><span key={tag}>{tag}</span>)}</div>{item.tier!=='free'&&<div className="di-lock"><strong>{accessLabel(item.tier)} content</strong><span>Requires verified entitlement.</span></div>}</article>)}</div>{!results.length&&<div className="di-empty">No current seed record matched this query. That is a real “no match” state — it does not fabricate an answer.</div>}</div>
}
