import {useMemo,useState} from 'react'
import {buildRecipe,recipeToTokens} from './engine.js'
import './DesignIntelligence.css'
const EXAMPLES=['Build a dark analytics dashboard for developers with a technical, premium feel.','Create a friendly healthcare web product with clear forms and accessible charts.','Design a luxury ecommerce landing page with an editorial mood.']
export default function DesignIntelligenceGenerator(){
  const [prompt,setPrompt]=useState(EXAMPLES[0]);const [submitted,setSubmitted]=useState(EXAMPLES[0]);const recipe=useMemo(()=>buildRecipe(submitted),[submitted]);const tokens=recipeToTokens(recipe)
  const previewStyle={background:recipe.palette.background,color:recipe.palette.text,'--di-accent':recipe.palette.accent,'--di-cta':recipe.palette.cta}
  return <div className="di-page"><section className="di-page-intro"><span className="di-kicker">GENERATE</span><h1>Build a Design Recipe</h1><p>Describe the product instead of manually choosing every field. This phase uses deterministic interpretation and the canonical seed catalog.</p></section><section className="di-generator-grid"><div className="di-surface"><label className="di-label" htmlFor="di-prompt">Your requirement</label><textarea id="di-prompt" className="di-prompt" value={prompt} onChange={e=>setPrompt(e.target.value)} rows={7}/><div className="di-example-row">{EXAMPLES.map(example=><button key={example} onClick={()=>setPrompt(example)}>{example}</button>)}</div><button className="di-btn di-btn-primary di-full" onClick={()=>setSubmitted(prompt)}>Generate recipe</button></div><div className="di-surface"><div className="di-record-head"><span className="di-record-domain">INTERPRETED REQUEST</span><span className="di-tier tier-free">Deterministic</span></div><div className="di-kv"><span>Product</span><b>{recipe.request.product}</b><span>Industry</span><b>{recipe.request.industry}</b><span>Platform</span><b>{recipe.request.platform}</b><span>Mode</span><b>{recipe.request.mode}</b><span>Mood</span><b>{recipe.request.mood}</b></div></div></section><section className="di-recipe-grid"><article className="di-surface"><span className="di-kicker">RECIPE</span><h2>{recipe.style.name} · {recipe.palette.name}</h2><p className="di-muted">{recipe.layout}</p><div className="di-recipe-list"><div><b>Typography</b><span>{recipe.typography.name}</span></div><div><b>Chart</b><span>{recipe.chart?.name||'Not required'}</span></div><div><b>Stack</b><span>{recipe.stack?.name}</span></div><div><b>Navigation</b><span>{recipe.navigation}</span></div><div><b>Access tier</b><span>{recipe.tier}</span></div></div>{recipe.warnings.map(w=><div className="di-warning" key={w}>⚠ {w}</div>)}</article><article className="di-preview" style={previewStyle}><div className="di-preview-nav"><span>MotionZync</span><span>Dashboard</span><span>Analytics</span><span>Settings</span></div><div className="di-preview-body"><div className="di-preview-kpi"><span>Signal</span><strong>84.7%</strong><small>+12.4%</small></div><div className="di-preview-chart"><span>Activity trend</span><div className="di-bars"><i/><i/><i/><i/><i/><i/><i/></div></div><div className="di-preview-cards"><div>Team <b>14</b></div><div>Projects <b>32</b></div><div>Latency <b>128ms</b></div></div></div></article></section><section className="di-surface"><div className="di-section-heading"><div><span className="di-kicker">TOKENS</span><h2>Generated design tokens</h2></div></div><pre className="di-code">{JSON.stringify(tokens,null,2)}</pre></section></div>
}
